version: 2
updates:
  - package-ecosystem: "cargo"
    directories:
      - "/"
    schedule:
      interval: "weekly"
    groups:
      minor/patch:
        update-types:
          - "patch"
          - "minor"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
